#!/bin/sh

if [ -z "$TFTP_SERVER" ]; then
  export TFTP_SERVER="localhost"
fi

DSTDIR="${USER}@${TFTP_SERVER}:/var/lib/tftpboot/"

echo "Copy to ${DSTDIR} from rpi_bcm283x/bin/ files."
scp ${BD}/bin/rpi_bcm283x/tmonitor.bin ${DSTDIR}
scp ${BD}/bin/rpi_bcm283x/rominfo-rom.bin ${DSTDIR}
scp ${BD}/bin/rpi_bcm283x/kernel-rom.bin ${DSTDIR}

